country_to_noc = {
    # 修正部分
    'United States': 'USA',
    'Greece': 'GRE',
    'Germany': 'GER',
    'France': 'FRA',
    'Great Britain': 'GBR',
    'United Kingdom': 'GBR',  # 添加 United Kingdom
    'Hungary': 'HUN',
    'Austria': 'AUT',
    'Australia': 'AUS',
    'Denmark': 'DEN',
    'Switzerland': 'SUI',
    'Mixed team': 'ZZX',  # 非正式队伍
    'Belgium': 'BEL',
    'Italy': 'ITA',
    'Cuba': 'CUB',
    'Canada': 'CAN',
    'Spain': 'ESP',
    'Luxembourg': 'LUX',
    'Norway': 'NOR',
    'Netherlands': 'NED',
    'India': 'IND',
    'Bohemia': 'BOH',  # 历史名称
    'Sweden': 'SWE',
    'Australasia': 'ANZ',  # 澳大利亚和新西兰联合队
    'Russian Empire': 'RU1',  # 俄国历史名称
    'Finland': 'FIN',
    'South Africa': 'RSA',
    'Estonia': 'EST',
    'Brazil': 'BRA',
    'Japan': 'JPN',
    'Czechoslovakia': 'TCH',  # 捷克斯洛伐克历史名称
    'New Zealand': 'NZL',
    'Yugoslavia': 'YUG',  # 南斯拉夫历史名称
    'Argentina': 'ARG',
    'Uruguay': 'URU',
    'Poland': 'POL',
    'Haiti': 'HAI',
    'Portugal': 'POR',
    'Romania': 'ROU',
    'Egypt': 'EGY',
    'Ireland': 'IRL',
    'Chile': 'CHI',
    'Philippines': 'PHI',
    'Mexico': 'MEX',
    'Latvia': 'LAT',
    'Turkey': 'TUR',
    'Jamaica': 'JAM',
    'Peru': 'PER',
    'Ceylon': 'CEY',  # 斯里兰卡的历史名称
    'Trinidad and Tobago': 'TTO',
    'Panama': 'PAN',
    'South Korea': 'KOR',
    'Iran': 'IRI',
    'Puerto Rico': 'PUR',
    'Soviet Union': 'URS',  # 苏联历史名称
    'Lebanon': 'LIB',
    'Bulgaria': 'BUL',
    'Venezuela': 'VEN',
    'United Team of Germany': 'EUA',  # 德国联合队历史名称
    'Iceland': 'ISL',
    'Pakistan': 'PAK',
    'Bahamas': 'BAH',
    'Ethiopia': 'ETH',
    'Formosa': 'TPE',  # 台湾的历史名称
    'Ghana': 'GHA',
    'Morocco': 'MAR',
    'Singapore': 'SGP',
    'British West Indies': 'BWI',  # 英属西印度群岛历史名称
    'Iraq': 'IRQ',
    'Tunisia': 'TUN',
    'Kenya': 'KEN',
    'Nigeria': 'NGR',
    'East Germany': 'GDR',  # 东德历史名称
    'West Germany': 'FRG',  # 西德历史名称
    'Mongolia': 'MGL',
    'Uganda': 'UGA',
    'Cameroon': 'CMR',
    'Taiwan': 'TPE',
    'North Korea': 'PRK',
    'Colombia': 'COL',
    'Niger': 'NIG',
    'Bermuda': 'BER',
    'Thailand': 'THA',
    'Zimbabwe': 'ZIM',
    'Tanzania': 'TAN',
    'Guyana': 'GUY',
    'China': 'CHN',
    'Ivory Coast': 'CIV',
    'Syria': 'SYR',
    'Algeria': 'ALG',
    'Chinese Taipei': 'TPE',
    'Dominican Republic': 'DOM',
    'Zambia': 'ZAM',
    'Suriname': 'SUR',
    'Costa Rica': 'CRC',
    'Indonesia': 'INA',
    'Netherlands Antilles': 'AHO',  # 荷属安的列斯历史名称
    'Senegal': 'SEN',
    'Virgin Islands': 'ISV',
    'Djibouti': 'DJI',
    'Unified Team': 'EUN',  # 独联体联合队历史名称
    'Lithuania': 'LTU',
    'Namibia': 'NAM',
    'Croatia': 'CRO',
    'Independent Olympic Participants': 'IOP',  # 独立参赛者
    'Israel': 'ISR',
    'Slovenia': 'SLO',
    'Malaysia': 'MAS',
    'Qatar': 'QAT',
    'Russia': 'RUS',
    'Ukraine': 'UKR',
    'Czech Republic': 'CZE',
    'Kazakhstan': 'KAZ',
    'Belarus': 'BLR',
    'FR Yugoslavia': 'YUG',
    'Slovakia': 'SVK',
    'Armenia': 'ARM',
    'Burundi': 'BDI',
    'Ecuador': 'ECU',
    'Hong Kong': 'HKG',
    'Moldova': 'MDA',
    'Uzbekistan': 'UZB',
    'Azerbaijan': 'AZE',
    'Tonga': 'TGA',
    'Georgia': 'GEO',
    'Mozambique': 'MOZ',
    'Saudi Arabia': 'KSA',
    'Sri Lanka': 'SRI',
    'Vietnam': 'VIE',
    'Barbados': 'BAR',
    'Kuwait': 'KUW',
    'Kyrgyzstan': 'KGZ',
    'Macedonia': 'MKD',
    'United Arab Emirates': 'UAE',
    'Serbia and Montenegro': 'SCG',  # 塞黑历史名称
    'Paraguay': 'PAR',
    'Eritrea': 'ERI',
    'Serbia': 'SRB',
    'Tajikistan': 'TJK',
    'Samoa': 'SAM',
    'Sudan': 'SUD',
    'Afghanistan': 'AFG',
    'Mauritius': 'MRI',
    'Togo': 'TOG',
    'Bahrain': 'BRN',
    'Grenada': 'GRN',
    'Botswana': 'BOT',
    'Cyprus': 'CYP',
    'Gabon': 'GAB',
    'Guatemala': 'GUA',
    'Montenegro': 'MNE',
    'Independent Olympic Athletes': 'IOA',
    'Fiji': 'FIJ',
    'Jordan': 'JOR',
    'Kosovo': 'KOS',
    'ROC': 'ROC',  # 俄罗斯奥委会
    'San Marino': 'SMR',
    'North Macedonia': 'MKD',
    'Turkmenistan': 'TKM',
    'Burkina Faso': 'BUR',
    'Saint Lucia': 'LCA',
    'Dominica': 'DMA',
    'Albania': 'ALB',
    'Cabo Verde': 'CPV',
    'Refugee Olympic Team': 'ROT',
    # 扩展部分
    'Chad': 'CHA',
    'Nicaragua': 'NCA',
    'United Arab Republic': 'UAR',
    'Libya': 'LBA',
    'Palestine': 'PLE',
    'Comoros': 'COM',
    'Brunei': 'BRU',
    'Maldives': 'MDV',
    'North Yemen': 'YAR',
    'Congo (Brazzaville)': 'CGO',
    'Monaco': 'MON',
    'Benin': 'BEN',
    'Somalia': 'SOM',
    'Mali': 'MLI',
    'Angola': 'ANG',
    'Bangladesh': 'BAN',
    'El Salvador': 'ESA',
    'Honduras': 'HON',
    'Seychelles': 'SEY',
    'Mauritania': 'MTN',
    'Saint Kitts and Nevis': 'SKN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Liberia': 'LBR',
    'Nepal': 'NEP',
    'Palau': 'PLW',
    'American Samoa': 'ASA',
    'Rwanda': 'RWA',
    'Malta': 'MLT',
    'Guinea': 'GUI',
    'Belize': 'BIZ',
    'South Yemen': 'YMD',
    'Sierra Leone': 'SLE',
    'Papua New Guinea': 'PNG',
    'Yemen': 'YEM',
    'Oman': 'OMA',
    'Vanuatu': 'VAN',
    'British Virgin Islands': 'IVB',
    'Central African Republic': 'CAF',
    'Madagascar': 'MAD',
    'Malaya': 'MAL',
    'Bosnia and Herzegovina': 'BIH',
    'Guam': 'GUM',
    'Cayman Islands': 'CAY',
    'Guinea Bissau': 'GBS',
    'Timor Leste': 'TLS',
    'Congo (Kinshasa)': 'COD',
    'Laos': 'LAO',
    'GyoshuII': 'CAM',
    'Solomon Islands': 'SOL',
    'Equatorial Guinea': 'GEQ',
    'Bolivia': 'BOL',
    'Saar': 'SAA',
    'Antigua and Barbuda': 'ANT',
    'Andorra': 'AND',
    'Federated States of Micronesia': 'FSM',
    'Myanmar': 'MYA',
    'Malawi': 'MAW',
    'Rhodesia': 'RHO',
    'Sao Tome and Principe': 'STP',
    'Liechtenstein': 'LIE',
    'Gambia': 'GAM',
    'Cook Islands': 'COK',
    'Circus': 'WIF',
    'Swaziland': 'SWZ',
    'North Borneo': 'NBO',
    'Aruba': 'ARU',
    'Nauru': 'NRU',
    'South Vietnam': 'VNM',
    'Bhutan': 'BHU',
    'Marshall Islands': 'MHL',
    'Kiribati': 'KIR',
    'Unknown': 'UNK',
    'Tuvalu': 'TUV',
    'Newfoundland': 'NFL',
    'South Sudan': 'SSD',
    'Lesotho': 'LES',
    'Refugee Olympic Team': 'EOR',
    'Lebanon': 'LBN',
    'AIN': 'AIN',
    # 'Lebanon': 'LIB',
    'Refugee Olympic Athletes': 'ROT'
    # 省略其他扩展部分，需根据真实情况补充...
}

country_mapping = {
    'Greece': 'GRE',
    'France': 'FRA',
    'United States': 'USA',
    'United Kingdom': 'GBR',
    'Sweden': 'SWE',
    'Belgium': 'BEL',
    'Netherlands': 'NED',
    'Germany': 'GER',
    'Finland': 'FIN',
    'Australia': 'AUS',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Mexico': 'MEX',
    'West Germany': 'FRG',  # FRG 是西德（West Germany）的简写
    'Canada': 'CAN',
    'Soviet Union': 'URS',
    'South Korea': 'KOR',
    'Spain': 'ESP',
    'China': 'CHN',
    'Brazil': 'BRA'
}
country_list = [
 'CHN', 'DEN', 'NED', 'FIN', 'NOR', 'ROU', 'EST', 'FRA', 'MAR', 'ESP', 'EGY', 'IRI',
 'BUL', 'ITA', 'CHA', 'AZE', 'SUD', 'RUS', 'ARG', 'CUB', 'BLR', 'GRE', 'CMR', 'TUR',
 'CHI', 'MEX', 'USA', 'URS', 'NCA', 'HUN', 'NGR', 'ALG', 'KUW', 'BRN', 'PAK', 'IRQ',
 'LBN', 'QAT', 'MAS', 'GER', 'CAN', 'IRL', 'AUS', 'RSA', 'ERI', 'TAN', 'JOR', 'TUN',
 'LBA', 'BEL', 'DJI', 'PLE', 'COM', 'KAZ', 'BRU', 'IND', 'KSA', 'SYR', 'MDV', 'ETH',
 'UAE', 'YAR', 'INA', 'PHI', 'SGP', 'UZB', 'KGZ', 'TJK', 'EUN', 'JPN', 'CGO', 'SUI',
 'BRA', 'GDR', 'MGL', 'ISR', 'URU', 'SWE', 'SRI', 'ARM', 'CIV', 'KEN', 'BEN', 'GBR',
 'GHA', 'SOM', 'MLI', 'AFG', 'POL', 'CRC', 'PAN', 'GEO', 'SLO', 'GUY', 'NZL', 'POR',
 'PAR', 'ANG', 'VEN', 'COL', 'FRG', 'BAN', 'PER', 'ESA', 'PUR', 'UGA', 'HON', 'ECU',
 'TKM', 'MRI', 'SEY', 'CZE', 'LUX', 'MTN', 'SKN', 'TTO', 'DOM', 'VIN', 'JAM', 'LBR',
 'SUR', 'NEP', 'AUT', 'PLW', 'LTU', 'TOG', 'NAM', 'AHO', 'UKR', 'ISL', 'ASA', 'SAM',
 'RWA', 'CRO', 'DMA', 'HAI', 'MLT', 'CYP', 'BIZ', 'YMD', 'THA', 'BER', 'ANZ', 'SCG',
 'SLE', 'PNG', 'YEM', 'TLS', 'OMA', 'FIJ', 'VAN', 'MDA', 'BAH', 'GUA', 'YUG', 'LAT',
 'SRB', 'IVB', 'MOZ', 'ISV', 'CAF', 'MAD', 'BIH', 'GUM', 'CAY', 'SVK', 'BAR', 'GBS',
 'COD', 'GAB', 'SMR', 'LAO', 'BOT', 'ROT', 'KOR', 'CAM', 'PRK', 'SOL', 'SEN', 'CPV',
 'GEQ', 'BOL', 'SAA', 'ANT', 'AND', 'ZIM', 'GRN', 'HKG', 'LCA', 'FSM', 'MYA', 'MAW',
 'ZAM', 'TPE', 'STP', 'MKD', 'BOH', 'LIE', 'MNE', 'GAM', 'ALB', 'WIF', 'SWZ', 'NBO',
 'BDI', 'ARU', 'NRU', 'VIE', 'BHU', 'MHL', 'KIR', 'UNK', 'TUV', 'TGA', 'NFL', 'KOS',
 'SSD', 'LES', 'EOR', 'AIN',
]

# 检查第一个字典是否正确涵盖了第二个字典的信息
def check_second_in_first(country_to_noc, country_mapping):
    missing_entries = {}
    for country, noc in country_mapping.items():
        if country not in country_to_noc:
            missing_entries[country] = noc
        elif country_to_noc[country] != noc:
            missing_entries[country] = {'expected': noc, 'found': country_to_noc[country]}
    return missing_entries

# 检查第一个字典是否正确涵盖了第三个列表的信息
def check_third_in_first(country_to_noc, country_list):
    all_nocs_in_first = set(country_to_noc.values())
    missing_nocs = [noc for noc in country_list if noc not in all_nocs_in_first]
    return missing_nocs

# 执行检查
missing_from_second = check_second_in_first(country_to_noc, country_mapping)
missing_from_third = check_third_in_first(country_to_noc, country_list)

# 输出检查结果
print("=== 检查结果 ===")
print(f"第一个字典未正确包含第二个字典的条目: {missing_from_second}")
print(f"第一个字典未正确包含第三个列表中所有的国家代码: {missing_from_third}")



### 用于修改的代码
country_to_noc = {
    # 修正部分
    'United States': 'USA',
    'Greece': 'GRE',
    'Germany': 'GER',
    'France': 'FRA',
    'Great Britain': 'GBR',
    'United Kingdom': 'GBR',  # 添加 United Kingdom
    'Hungary': 'HUN',
    'Austria': 'AUT',
    'Australia': 'AUS',
    'Denmark': 'DEN',
    'Switzerland': 'SUI',
    'Mixed team': 'ZZX',  # 非正式队伍
    'Belgium': 'BEL',
    'Italy': 'ITA',
    'Cuba': 'CUB',
    'Canada': 'CAN',
    'Spain': 'ESP',
    'Luxembourg': 'LUX',
    'Norway': 'NOR',
    'Netherlands': 'NED',
    'India': 'IND',
    'Bohemia': 'BOH',  # 历史名称
    'Sweden': 'SWE',
    'Australasia': 'ANZ',  # 澳大利亚和新西兰联合队
    'Russian Empire': 'RU1',  # 俄国历史名称
    'Finland': 'FIN',
    'South Africa': 'RSA',
    'Estonia': 'EST',
    'Brazil': 'BRA',
    'Japan': 'JPN',
    'Czechoslovakia': 'TCH',  # 捷克斯洛伐克历史名称
    'New Zealand': 'NZL',
    'Yugoslavia': 'YUG',  # 南斯拉夫历史名称
    'Argentina': 'ARG',
    'Uruguay': 'URU',
    'Poland': 'POL',
    'Haiti': 'HAI',
    'Portugal': 'POR',
    'Romania': 'ROU',
    'Egypt': 'EGY',
    'Ireland': 'IRL',
    'Chile': 'CHI',
    'Philippines': 'PHI',
    'Mexico': 'MEX',
    'Latvia': 'LAT',
    'Turkey': 'TUR',
    'Jamaica': 'JAM',
    'Peru': 'PER',
    'Ceylon': 'CEY',  # 斯里兰卡的历史名称
    'Trinidad and Tobago': 'TTO',
    'Panama': 'PAN',
    'South Korea': 'KOR',
    'Iran': 'IRI',
    'Puerto Rico': 'PUR',
    'Soviet Union': 'URS',  # 苏联历史名称
    'Lebanon': 'LIB',
    'Bulgaria': 'BUL',
    'Venezuela': 'VEN',
    'United Team of Germany': 'EUA',  # 德国联合队历史名称
    'Iceland': 'ISL',
    'Pakistan': 'PAK',
    'Bahamas': 'BAH',
    'Ethiopia': 'ETH',
    'Formosa': 'TPE',  # 台湾的历史名称
    'Ghana': 'GHA',
    'Morocco': 'MAR',
    'Singapore': 'SGP',
    'British West Indies': 'BWI',  # 英属西印度群岛历史名称
    'Iraq': 'IRQ',
    'Tunisia': 'TUN',
    'Kenya': 'KEN',
    'Nigeria': 'NGR',
    'East Germany': 'GDR',  # 东德历史名称
    'West Germany': 'FRG',  # 西德历史名称
    'Mongolia': 'MGL',
    'Uganda': 'UGA',
    'Cameroon': 'CMR',
    'Taiwan': 'TPE',
    'North Korea': 'PRK',
    'Colombia': 'COL',
    'Niger': 'NIG',
    'Bermuda': 'BER',
    'Thailand': 'THA',
    'Zimbabwe': 'ZIM',
    'Tanzania': 'TAN',
    'Guyana': 'GUY',
    'China': 'CHN',
    'Ivory Coast': 'CIV',
    'Syria': 'SYR',
    'Algeria': 'ALG',
    'Chinese Taipei': 'TPE',
    'Dominican Republic': 'DOM',
    'Zambia': 'ZAM',
    'Suriname': 'SUR',
    'Costa Rica': 'CRC',
    'Indonesia': 'INA',
    'Netherlands Antilles': 'AHO',  # 荷属安的列斯历史名称
    'Senegal': 'SEN',
    'Virgin Islands': 'ISV',
    'Djibouti': 'DJI',
    'Unified Team': 'EUN',  # 独联体联合队历史名称
    'Lithuania': 'LTU',
    'Namibia': 'NAM',
    'Croatia': 'CRO',
    'Independent Olympic Participants': 'IOP',  # 独立参赛者
    'Israel': 'ISR',
    'Slovenia': 'SLO',
    'Malaysia': 'MAS',
    'Qatar': 'QAT',
    'Russia': 'RUS',
    'Ukraine': 'UKR',
    'Czech Republic': 'CZE',
    'Kazakhstan': 'KAZ',
    'Belarus': 'BLR',
    'FR Yugoslavia': 'YUG',
    'Slovakia': 'SVK',
    'Armenia': 'ARM',
    'Burundi': 'BDI',
    'Ecuador': 'ECU',
    'Hong Kong': 'HKG',
    'Moldova': 'MDA',
    'Uzbekistan': 'UZB',
    'Azerbaijan': 'AZE',
    'Tonga': 'TGA',
    'Georgia': 'GEO',
    'Mozambique': 'MOZ',
    'Saudi Arabia': 'KSA',
    'Sri Lanka': 'SRI',
    'Vietnam': 'VIE',
    'Barbados': 'BAR',
    'Kuwait': 'KUW',
    'Kyrgyzstan': 'KGZ',
    'Macedonia': 'MKD',
    'United Arab Emirates': 'UAE',
    'Serbia and Montenegro': 'SCG',  # 塞黑历史名称
    'Paraguay': 'PAR',
    'Eritrea': 'ERI',
    'Serbia': 'SRB',
    'Tajikistan': 'TJK',
    'Samoa': 'SAM',
    'Sudan': 'SUD',
    'Afghanistan': 'AFG',
    'Mauritius': 'MRI',
    'Togo': 'TOG',
    'Bahrain': 'BRN',
    'Grenada': 'GRN',
    'Botswana': 'BOT',
    'Cyprus': 'CYP',
    'Gabon': 'GAB',
    'Guatemala': 'GUA',
    'Montenegro': 'MNE',
    'Independent Olympic Athletes': 'IOA',
    'Fiji': 'FIJ',
    'Jordan': 'JOR',
    'Kosovo': 'KOS',
    'ROC': 'ROC',  # 俄罗斯奥委会
    'San Marino': 'SMR',
    'North Macedonia': 'MKD',
    'Turkmenistan': 'TKM',
    'Burkina Faso': 'BUR',
    'Saint Lucia': 'LCA',
    'Dominica': 'DMA',
    'Albania': 'ALB',
    'Cabo Verde': 'CPV',
    'Refugee Olympic Team': 'ROT',
    # 扩展部分
    'Chad': 'CHA',
    'Nicaragua': 'NCA',
    'United Arab Republic': 'UAR',
    'Libya': 'LBA',
    'Palestine': 'PLE',
    'Comoros': 'COM',
    'Brunei': 'BRU',
    'Maldives': 'MDV',
    'North Yemen': 'YAR',
    'Congo (Brazzaville)': 'CGO',
    'Monaco': 'MON',
    'Benin': 'BEN',
    'Somalia': 'SOM',
    'Mali': 'MLI',
    'Angola': 'ANG',
    'Bangladesh': 'BAN',
    'El Salvador': 'ESA',
    'Honduras': 'HON',
    'Seychelles': 'SEY',
    'Mauritania': 'MTN',
    'Saint Kitts and Nevis': 'SKN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Liberia': 'LBR',
    'Nepal': 'NEP',
    'Palau': 'PLW',
    'American Samoa': 'ASA',
    'Rwanda': 'RWA',
    'Malta': 'MLT',
    'Guinea': 'GUI',
    'Belize': 'BIZ',
    'South Yemen': 'YMD',
    'Sierra Leone': 'SLE',
    'Papua New Guinea': 'PNG',
    'Yemen': 'YEM',
    'Oman': 'OMA',
    'Vanuatu': 'VAN',
    'British Virgin Islands': 'IVB',
    'Central African Republic': 'CAF',
    'Madagascar': 'MAD',
    'Malaya': 'MAL',
    'Bosnia and Herzegovina': 'BIH',
    'Guam': 'GUM',
    'Cayman Islands': 'CAY',
    'Guinea Bissau': 'GBS',
    'Timor Leste': 'TLS',
    'Congo (Kinshasa)': 'COD',
    'Laos': 'LAO',
    'GyoshuII': 'CAM',
    'Solomon Islands': 'SOL',
    'Equatorial Guinea': 'GEQ',
    'Bolivia': 'BOL',
    'Saar': 'SAA',
    'Antigua and Barbuda': 'ANT',
    'Andorra': 'AND',
    'Federated States of Micronesia': 'FSM',
    'Myanmar': 'MYA',
    'Malawi': 'MAW',
    'Rhodesia': 'RHO',
    'Sao Tome and Principe': 'STP',
    'Liechtenstein': 'LIE',
    'Gambia': 'GAM',
    'Cook Islands': 'COK',
    'Circus': 'WIF',
    'Swaziland': 'SWZ',
    'North Borneo': 'NBO',
    'Aruba': 'ARU',
    'Nauru': 'NRU',
    'South Vietnam': 'VNM',
    'Bhutan': 'BHU',
    'Marshall Islands': 'MHL',
    'Kiribati': 'KIR',
    'Unknown': 'UNK',
    'Tuvalu': 'TUV',
    'Newfoundland': 'NFL',
    'South Sudan': 'SSD',
    'Lesotho': 'LES',
    'Refugee Olympic Team': 'EOR',
    'Lebanon': 'LBN',
    'AIN': 'AIN',
    # 'Lebanon': 'LIB',
    'Refugee Olympic Athletes': 'ROT'
    # 省略其他扩展部分，需根据真实情况补充...
}

all_nocs_in_first = set(country_to_noc.values())
missing_nocs = [noc for noc in country_list if noc not in all_nocs_in_first]
for noc in country_list:
    if noc in missing_nocs:
        key = athlete_data.loc[athlete_data['NOC'] == noc, 'Team'].values[0]
        print(f"'{key}': '{noc}',")